services:

  backend:
    image: home4paws-backend
    container_name: home4paws-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.fdnngmfcveylwgkwjrov
      SPRING_DATASOURCE_PASSWORD: Chir@989707
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    image: home4paws-frontend
    container_name: home4paws-frontend
    depends_on:
      - backend
    ports:
      - "4173:4173"
