spring.application.name=home4paws
#PostgreSql
spring.datasource.url=jdbc:postgresql://localhost:5432/home4paws
spring.datasource.username=postgres
spring.datasource.password=Chir@3175
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# server
server.port=8080