spring.datasource.url=jdbc:postgresql://localhost:5432/home4paws
spring.datasource.username=postgres
spring.datasource.password=Chir@3175

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081