spring.application.name=home4paws

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/home4paws
spring.datasource.username=postgres
spring.datasource.password=Chir@3175
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080

# JWT Configuration
jwt.secret=home4paws_super_secret_key_that_is_at_least_256_bits_long_for_hmac
jwt.expiration=86400000
