# spring.application.name=home4paws

# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
# # spring.datasource.username=postgres.fdnngmfcveylwgkwjrov
# # spring.datasource.password=Chir@3175
# spring.datasource.username=TEST_USERNAME_12345
# spring.datasource.password=TEST_PASSWORD_12345
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.open-in-view=false

# server.port=8080

# jwt.secret=home4paws_super_secret_key_that_is_at_least_256_bits_long_for_hmac
# jwt.expiration=86400000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fdnngmfcveylwgkwjrov
spring.datasource.password=Chir@989707

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081